const app=document.querySelector('#app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let questions=[],step=-1,state={name:'',answers:{},note:'',id:crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2)},rows=[];
try{const draft=JSON.parse(localStorage.getItem('game-survey-draft'));if(draft?.id)state=draft;}catch{}
const save=()=>{try{localStorage.setItem('game-survey-draft',JSON.stringify(state));}catch{}};
async function api(url,options={}){const target=url==='/api/questions'&&location.hostname.endsWith('github.io')?'./questions.json':(window.SURVEY_API||'')+url;let r;try{r=await fetch(target,{...options,signal:AbortSignal.timeout(20000)});}catch{throw Error('сервер ответов сейчас недоступен — сообщи организатору');}const b=await r.json();if(!r.ok)throw Error(b.error||'Ошибка сервера');return b;}
function error(message){const el=document.querySelector('#error');if(el)el.textContent=message;}
function render(){
 if(step===-1){app.innerHTML=`<div class="intro"><div><span class="badge">12 вопросов · около 3 минут</span><h1>Какую игру<br>мы хотим?</h1><p class="muted">Расскажи, что тебе нравится. Из ответов нашей компании соберём идею новой игры.</p></div><div class="ticket" aria-hidden="true">✚</div></div><form id="start"><label class="name" for="name">Сначала — как тебя зовут?</label><input id="name" type="text" maxlength="50" required autocomplete="given-name" placeholder="Имя или ник" value="${esc(state.name)}"><p class="muted">Имя подпишет твои ответы. Можно указать ник.</p><div class="actions"><button>Начать опрос</button></div><p id="error" class="error" role="alert"></p></form>`;document.querySelector('#start').onsubmit=e=>{e.preventDefault();state.name=document.querySelector('#name').value.trim();if(!state.name)return error('Напиши имя или ник.');save();step=0;render();};return;}
 if(step===questions.length){app.innerHTML=`<span class="badge">Почти готово, ${esc(state.name)}</span><h1>Что ещё стоит знать?</h1><p class="muted">Необязательно: любимые режимы Roblox, другие игры или твоя идея.</p><textarea id="note" maxlength="1500" placeholder="Например: в Roblox люблю…">${esc(state.note)}</textarea><p class="muted">После отправки организатор увидит твои ответы.</p><div class="actions"><button class="secondary" id="back">Назад</button><button id="send">Отправить ответы</button></div><p id="error" class="error" role="alert"></p>`;document.querySelector('#note').oninput=e=>{state.note=e.target.value;save();};document.querySelector('#back').onclick=()=>{step--;render();};document.querySelector('#send').onclick=async e=>{e.target.disabled=true;error('');try{await api('/api/answers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});try{localStorage.removeItem('game-survey-draft');}catch{}app.innerHTML=`<div class="successmark">✓</div><h1>Ответы отправлены!</h1><p>${esc(state.name)}, спасибо! Организатор уже может посмотреть, во что тебе интересно играть.</p><p class="muted">Можно закрыть страницу.</p>`;}catch(err){error('Не удалось отправить: '+err.message+'. Ответы сохранены в этом браузере.');e.target.disabled=false;}};return;}
 const q=questions[step];app.innerHTML=`<div class="meta"><span>${esc(state.name)}</span><span>Вопрос ${step+1} из ${questions.length}</span></div><div class="progressline"><div style="width:0" id="progress"></div></div><h2>${esc(q.title)}</h2><p class="muted">${q.multi?'Можно выбрать несколько вариантов.':'Выбери один вариант.'}</p><form id="question"><div class="options">${q.options.map((o,i)=>`<label class="option"><input type="${q.multi?'checkbox':'radio'}" name="answer" value="${esc(o)}" ${(state.answers[q.id]||[]).includes(o)?'checked':''}><span>${esc(o)}</span></label>`).join('')}</div><p id="error" class="error" role="alert"></p><div class="actions"><button type="button" class="secondary" id="back">Назад</button><button>Дальше</button></div></form>`;document.querySelector('#progress').style.width=((step+1)/questions.length*100)+'%';document.querySelector('#question').onchange=()=>{state.answers[q.id]=[...document.querySelectorAll('input:checked')].map(i=>i.value);save();error('');};document.querySelector('#question').onsubmit=e=>{e.preventDefault();if(!state.answers[q.id]?.length)return error('Выбери хотя бы один вариант.');step++;render();window.scrollTo(0,0);};document.querySelector('#back').onclick=()=>{step--;render();};
}
function exportText(){return 'Ответы друзей для выбора идеи игры\n\n'+rows.map(r=>`${r.name}\n${questions.map(q=>q.title+'\n'+r.answers[q.id].join(', ')).join('\n\n')}\nДополнение: ${r.note||'нет'}\n`).join('\n--------------------\n\n');}
function login(){app.innerHTML='<span class="badge">Для организатора</span><h1>Ответы друзей</h1><p class="muted">Введи PIN-код владельца, чтобы посмотреть результаты.</p><form id="login"><label class="name" for="pin">PIN-код</label><input id="pin" type="password" inputmode="numeric" required autocomplete="current-password"><div class="actions"><button>Показать ответы</button></div><p id="error" class="error" role="alert"></p></form>';document.querySelector('#login').onsubmit=async e=>{e.preventDefault();try{const b=await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:document.querySelector('#pin').value})});sessionStorage.setItem('survey-token',b.token);await results();}catch(err){error(err.message);}};}
async function results(){try{rows=await api('/api/results',{headers:{Authorization:'Bearer '+sessionStorage.getItem('survey-token')}});}catch{login();return;}app.innerHTML=`<span class="badge">Для организатора</span><h1>Ответы друзей <small>(${rows.length})</small></h1><p class="muted">Скопируй результаты и отправь в чат — по ним можно подобрать идею игры.</p><div class="toolbar"><button id="copy">Скопировать ответы</button><button class="secondary" id="download">Скачать .txt</button><button class="secondary" id="refresh">Обновить</button><button class="secondary" id="logout">Выйти</button></div><p id="error" role="status"></p><textarea id="export" class="hidden export" readonly aria-label="Ответы для копирования"></textarea>${rows.length?rows.map(r=>`<article class="results"><h3>${esc(r.name)}</h3><span class="muted">${esc(new Date(r.date).toLocaleString('ru-RU'))}</span><dl>${questions.map(q=>`<dt>${esc(q.title)}</dt><dd>${esc(r.answers[q.id].join(', '))}</dd>`).join('')}<dt>Дополнение</dt><dd>${esc(r.note||'Не указано')}</dd></dl></article>`).join(''):'<p>Пока ответов нет. Отправь друзьям ссылку на главную страницу опроса, затем нажми «Обновить».</p>'}`;document.querySelector('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(exportText());error('Скопировано — можно вставить в чат.');}catch{const el=document.querySelector('#export');el.classList.remove('hidden');el.value=exportText();el.focus();el.select();error('Выделенные ответы можно скопировать вручную.');}};document.querySelector('#download').onclick=()=>{const url=URL.createObjectURL(new Blob([exportText()],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ответы-друзей.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};document.querySelector('#refresh').onclick=results;document.querySelector('#logout').onclick=()=>{sessionStorage.removeItem('survey-token');login();};}
api('/api/questions').then(q=>{questions=q;if(location.pathname==='/admin'||location.hash==='#admin')results();else{if(state.name){const next=questions.findIndex(item=>!state.answers?.[item.id]?.length);step=next<0?questions.length:next;}render();}}).catch(()=>{app.innerHTML='<h1>Не удалось загрузить опрос</h1><p>Проверь соединение и обнови страницу.</p>';});
