const app = document.querySelector('#app');
const isPages = location.hostname.endsWith('github.io');
const esc = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let questions = [], step = -1, rows = [], importMessage = '';
let state = {name:'', answers:{}, note:'', id:crypto.randomUUID ? crypto.randomUUID() : Date.now()+'-'+Math.random().toString(36).slice(2)};
try { const draft=JSON.parse(localStorage.getItem('game-survey-draft')); if(draft?.id) state=draft; } catch {}
const save=()=>{try{localStorage.setItem('game-survey-draft',JSON.stringify(state));}catch{}};
const error=message=>{const el=document.querySelector('#error');if(el)el.textContent=message;};
async function api(url,options={}){let response;try{response=await fetch((window.SURVEY_API||'')+url,{...options,signal:AbortSignal.timeout(20000)});}catch{throw Error('сервер ответов сейчас недоступен');}const body=await response.json();if(!response.ok)throw Error(body.error||'Ошибка сервера');return body;}
function responseFromState(){return{id:state.id,name:state.name.trim(),answers:state.answers,note:state.note.trim(),date:new Date().toISOString()};}
function encodeResponse(response){const compact={v:1,i:response.id,n:response.name,a:questions.map(q=>response.answers[q.id].map(value=>q.options.indexOf(value))),x:response.note,d:response.date};const bytes=new TextEncoder().encode(JSON.stringify(compact));let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
function decodeResponse(code){if(!code||code.length>12000)throw Error();const base64=code.replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-code.length%4)%4);const bytes=Uint8Array.from(atob(base64),char=>char.charCodeAt(0));const data=JSON.parse(new TextDecoder().decode(bytes));if(data.v!==1||typeof data.i!=='string'||typeof data.n!=='string'||!data.n.trim()||data.n.length>50||!Array.isArray(data.a)||data.a.length!==questions.length||typeof data.x!=='string'||data.x.length>1500)throw Error();const answers={};questions.forEach((q,index)=>{const indexes=data.a[index];if(!Array.isArray(indexes)||!indexes.length||indexes.some(i=>!Number.isInteger(i)||i<0||i>=q.options.length)||(!q.multi&&indexes.length!==1))throw Error();answers[q.id]=[...new Set(indexes)].map(i=>q.options[i]);});return{id:data.i,name:data.n.trim(),answers,note:data.x.trim(),date:data.d||new Date().toISOString()};}
function loadLocalRows(){try{const saved=JSON.parse(localStorage.getItem('game-survey-results'));return Array.isArray(saved)?saved:[];}catch{return[];}}
function storeLocalRow(row){const saved=loadLocalRows();const position=saved.findIndex(item=>item.id===row.id);if(position>=0)saved[position]=row;else saved.push(row);localStorage.setItem('game-survey-results',JSON.stringify(saved));}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true;}catch{return false;}}
function showShare(response){const url=`${location.origin}${location.pathname}#response=${encodeResponse(response)}`;app.innerHTML=`<div class="successmark">✓</div><h1>Анкета готова!</h1><p><strong>${esc(response.name)}</strong>, остался последний шаг: отправь ссылку организатору в Telegram, WhatsApp или другом чате.</p><div class="actions"><button id="share">Отправить организатору</button><button class="secondary" id="copy-link">Скопировать ссылку</button></div><p id="error" class="error" role="status"></p><p class="muted">Только человек, которому ты отправишь ссылку, получит эти ответы.</p>`;document.querySelector('#share').onclick=async()=>{if(navigator.share){try{await navigator.share({title:'Мои ответы про игру',text:`Ответы ${response.name} для выбора игры`,url});localStorage.removeItem('game-survey-draft');error('Отправлено! Теперь можно закрыть страницу.');}catch(e){if(e.name!=='AbortError')error('Не получилось открыть отправку. Нажми «Скопировать ссылку».');}}else error('Нажми «Скопировать ссылку» и отправь её организатору в чате.');};document.querySelector('#copy-link').onclick=async()=>{if(await copyText(url)){localStorage.removeItem('game-survey-draft');error('Ссылка скопирована. Отправь её организатору в чате.');}else prompt('Скопируй эту ссылку и отправь организатору:',url);};}
function render(){
 if(step===-1){app.innerHTML=`<div class="intro"><div><span class="badge">12 вопросов · около 3 минут</span><h1>Какую игру<br>мы хотим?</h1><p class="muted">Расскажи, что тебе нравится. Из ответов нашей компании соберём идею новой игры.</p></div><div class="ticket" aria-hidden="true">✚</div></div><form id="start"><label class="name" for="name">Сначала — как тебя зовут?</label><input id="name" type="text" maxlength="50" required autocomplete="given-name" placeholder="Имя или ник" value="${esc(state.name)}"><p class="muted">Имя подпишет твои ответы. Можно указать ник.</p><div class="actions"><button>Начать опрос</button></div><p id="error" class="error" role="alert"></p></form>`;document.querySelector('#start').onsubmit=event=>{event.preventDefault();state.name=document.querySelector('#name').value.trim();if(!state.name)return error('Напиши имя или ник.');save();step=0;render();};return;}
 if(step===questions.length){app.innerHTML=`<span class="badge">Почти готово, ${esc(state.name)}</span><h1>Что ещё стоит знать?</h1><p class="muted">Необязательно: любимые режимы Roblox, другие игры или твоя идея.</p><textarea id="note" maxlength="1500" placeholder="Например: в Roblox люблю…">${esc(state.note)}</textarea><p class="muted">После заполнения отправь организатору готовую ссылку с ответами.</p><div class="actions"><button class="secondary" id="back">Назад</button><button id="send">Закончить опрос</button></div><p id="error" class="error" role="alert"></p>`;document.querySelector('#note').oninput=event=>{state.note=event.target.value;save();};document.querySelector('#back').onclick=()=>{step--;render();};document.querySelector('#send').onclick=async event=>{event.target.disabled=true;error('');if(isPages)return showShare(responseFromState());try{await api('/api/answers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});localStorage.removeItem('game-survey-draft');app.innerHTML=`<div class="successmark">✓</div><h1>Ответы отправлены!</h1><p>${esc(state.name)}, спасибо! Организатор уже может посмотреть твои ответы.</p>`;}catch(err){error('Не удалось отправить: '+err.message+'. Ответы сохранены в этом браузере.');event.target.disabled=false;}};return;}
 const q=questions[step];app.innerHTML=`<div class="meta"><span>${esc(state.name)}</span><span>Вопрос ${step+1} из ${questions.length}</span></div><div class="progressline"><div style="width:${(step+1)/questions.length*100}%"></div></div><h2>${esc(q.title)}</h2><p class="muted">${q.multi?'Можно выбрать несколько вариантов.':'Выбери один вариант.'}</p><form id="question"><div class="options">${q.options.map(o=>`<label class="option"><input type="${q.multi?'checkbox':'radio'}" name="answer" value="${esc(o)}" ${(state.answers[q.id]||[]).includes(o)?'checked':''}><span>${esc(o)}</span></label>`).join('')}</div><p id="error" class="error" role="alert"></p><div class="actions"><button type="button" class="secondary" id="back">Назад</button><button>Дальше</button></div></form>`;document.querySelector('#question').onchange=()=>{state.answers[q.id]=[...document.querySelectorAll('input:checked')].map(input=>input.value);save();error('');};document.querySelector('#question').onsubmit=event=>{event.preventDefault();if(!state.answers[q.id]?.length)return error('Выбери хотя бы один вариант.');step++;render();window.scrollTo(0,0);};document.querySelector('#back').onclick=()=>{step--;render();};
}
function exportText(){return'Ответы друзей для выбора идеи игры\n\n'+rows.map(r=>`${r.name}\n${questions.map(q=>q.title+'\n'+r.answers[q.id].join(', ')).join('\n\n')}\nДополнение: ${r.note||'нет'}\n`).join('\n--------------------\n\n');}
function renderResults(){app.innerHTML=`<span class="badge">Для организатора</span><h1>Ответы друзей <small>(${rows.length})</small></h1><p class="muted">Каждый друг после опроса отправляет тебе ссылку. Открой её — ответ появится здесь и сохранится в этом браузере.</p>${importMessage?`<p class="notice">${esc(importMessage)}</p>`:''}<div class="toolbar"><button id="copy">Скопировать ответы</button><button class="secondary" id="download">Скачать .txt</button><a class="button-link" href="./">Открыть опрос</a></div><p id="error" role="status"></p><textarea id="export" class="hidden export" readonly aria-label="Ответы для копирования"></textarea>${rows.length?rows.map(r=>`<article class="results"><h3>${esc(r.name)}</h3><span class="muted">${esc(new Date(r.date).toLocaleString('ru-RU'))}</span><dl>${questions.map(q=>`<dt>${esc(q.title)}</dt><dd>${esc(r.answers[q.id].join(', '))}</dd>`).join('')}<dt>Дополнение</dt><dd>${esc(r.note||'Не указано')}</dd></dl></article>`).join(''):'<p>Пока ответов нет. Открой ссылку с ответами, которую пришлёт друг.</p>'}`;document.querySelector('#copy').onclick=async()=>{if(await copyText(exportText()))error('Скопировано — можно вставить в чат.');else{const el=document.querySelector('#export');el.classList.remove('hidden');el.value=exportText();el.focus();el.select();error('Выделенные ответы можно скопировать вручную.');}};document.querySelector('#download').onclick=()=>{const url=URL.createObjectURL(new Blob([exportText()],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ответы-друзей.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};}
async function results(){if(isPages){rows=loadLocalRows();renderResults();return;}try{rows=await api('/api/results',{headers:{Authorization:'Bearer '+sessionStorage.getItem('survey-token')}});renderResults();}catch{login();}}
function login(){app.innerHTML='<span class="badge">Для организатора</span><h1>Ответы друзей</h1><p class="muted">Введи PIN-код владельца.</p><form id="login"><label class="name" for="pin">PIN-код</label><input id="pin" type="password" inputmode="numeric" required><div class="actions"><button>Показать ответы</button></div><p id="error" class="error" role="alert"></p></form>';document.querySelector('#login').onsubmit=async event=>{event.preventDefault();try{const body=await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:document.querySelector('#pin').value})});sessionStorage.setItem('survey-token',body.token);await results();}catch(err){error(err.message);}};}
fetch('./questions.json',{signal:AbortSignal.timeout(15000)}).then(response=>response.json()).then(loaded=>{questions=loaded;if(location.hash.startsWith('#response=')){try{const row=decodeResponse(location.hash.slice(10));storeLocalRow(row);importMessage=`Ответ «${row.name}» добавлен.`;history.replaceState(null,'',location.pathname+'#admin');results();}catch{app.innerHTML='<h1>Ссылка повреждена</h1><p>Попроси друга снова скопировать ссылку с ответами.</p>';}}else if(location.pathname==='/admin'||location.hash==='#admin')results();else{if(state.name){const next=questions.findIndex(item=>!state.answers?.[item.id]?.length);step=next<0?questions.length:next;}render();}}).catch(()=>{app.innerHTML='<h1>Не удалось загрузить опрос</h1><p>Проверь соединение и обнови страницу.</p>';});
